import type {
  User,
  Project,
  Task,
  Issue,
  Invitation,
  Notification,
  ActivityLog,
  Comment,
  DashboardStats,
  RoleDistribution,
  Sprint,
  BurndownPoint,
  StandupSession,
} from '../types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    email: 'john.doe@company.com',
    full_name: 'John Doe',
    avatar_url: 'https://randomuser.me/api/portraits/men/32.jpg',
    role: 'admin',
    status: 'active',
    designation: 'Senior Product Manager',
    department: 'Product Department',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    bio: 'Senior product manager with 10+ years of experience in tech.',
    joined_at: '2024-01-15',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    email: 'sarah.j@company.com',
    full_name: 'Sarah Johnson',
    avatar_url: 'https://randomuser.me/api/portraits/women/44.jpg',
    role: 'project_lead',
    status: 'active',
    designation: 'Project Lead',
    department: 'Engineering',
    joined_at: '2024-02-20',
    created_at: '2024-02-20T10:00:00Z',
    updated_at: '2024-02-20T10:00:00Z',
  },
  {
    id: '3',
    email: 'm.chen@company.com',
    full_name: 'Michael Chen',
    avatar_url: 'https://randomuser.me/api/portraits/men/67.jpg',
    role: 'developer',
    status: 'active',
    designation: 'Senior Developer',
    department: 'Engineering',
    joined_at: '2024-03-10',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    email: 'emily.d@company.com',
    full_name: 'Emily Davis',
    avatar_url: 'https://randomuser.me/api/portraits/women/28.jpg',
    role: 'designer',
    status: 'active',
    designation: 'UI/UX Designer',
    department: 'Design',
    joined_at: '2024-03-22',
    created_at: '2024-03-22T10:00:00Z',
    updated_at: '2024-03-22T10:00:00Z',
  },
  {
    id: '5',
    email: 'j.wilson@company.com',
    full_name: 'James Wilson',
    avatar_url: 'https://randomuser.me/api/portraits/men/52.jpg',
    role: 'qa',
    status: 'inactive',
    designation: 'QA Engineer',
    department: 'Quality',
    joined_at: '2024-02-05',
    created_at: '2024-02-05T10:00:00Z',
    updated_at: '2024-02-05T10:00:00Z',
  },
  {
    id: '6',
    email: 'lisa.a@company.com',
    full_name: 'Lisa Anderson',
    avatar_url: 'https://randomuser.me/api/portraits/women/15.jpg',
    role: 'developer',
    status: 'pending',
    designation: 'Frontend Developer',
    department: 'Engineering',
    joined_at: '2024-03-25',
    created_at: '2024-03-25T10:00:00Z',
    updated_at: '2024-03-25T10:00:00Z',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Veltroqis Platform',
    description: 'Core platform development including auth, user management, and integrations.',
    status: 'active',
    lead_id: '2',
    lead: MOCK_USERS[1],
    start_date: '2024-01-01',
    deadline: '2024-06-30',
    created_by: '1',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[3]],
    task_count: 24,
    completed_task_count: 16,
  },
  {
    id: 'p2',
    name: 'Mobile App Redesign',
    description: 'Redesigning the mobile application for better UX and performance.',
    status: 'active',
    lead_id: '1',
    lead: MOCK_USERS[0],
    start_date: '2024-02-01',
    deadline: '2024-05-15',
    created_by: '1',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-03-15T00:00:00Z',
    members: [MOCK_USERS[0], MOCK_USERS[3], MOCK_USERS[5]],
    task_count: 18,
    completed_task_count: 7,
  },
  {
    id: 'p3',
    name: 'API Gateway v2',
    description: 'Building the next generation API gateway with rate limiting and auth.',
    status: 'on_hold',
    lead_id: '2',
    lead: MOCK_USERS[1],
    start_date: '2024-03-01',
    deadline: '2024-07-31',
    created_by: '1',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-20T00:00:00Z',
    members: [MOCK_USERS[1], MOCK_USERS[2]],
    task_count: 12,
    completed_task_count: 3,
  },
  {
    id: 'p4',
    name: 'Analytics Dashboard',
    description: 'Real-time analytics and reporting dashboard for business insights.',
    status: 'completed',
    lead_id: '3',
    lead: MOCK_USERS[2],
    start_date: '2023-10-01',
    deadline: '2024-01-31',
    created_by: '1',
    created_at: '2023-10-01T00:00:00Z',
    updated_at: '2024-01-31T00:00:00Z',
    members: [MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[4]],
    task_count: 32,
    completed_task_count: 32,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    project_id: 'p1',
    title: 'Implement OAuth 2.0 authentication',
    description: 'Add Google and GitHub OAuth providers using Supabase Auth.',
    status: 'done',
    priority: 'high',
    assignee_ids: ['3'],
    assignees: [MOCK_USERS[2]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-03-28',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
    comment_count: 5,
    order_index: 0,
    labels: ['feature'],
    story_points: 8,
    sprint_id: 's1',
  },
  {
    id: 't2',
    project_id: 'p1',
    title: 'Design user onboarding flow',
    description: 'Create wireframes and prototypes for the new user onboarding experience.',
    status: 'in_progress',
    priority: 'medium',
    assignee_ids: ['4'],
    assignees: [MOCK_USERS[3]],
    reporter_id: '2',
    reporter: MOCK_USERS[1],
    due_date: '2026-04-05',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-30T10:00:00Z',
    comment_count: 3,
    order_index: 1,
    labels: ['design'],
    story_points: 5,
    sprint_id: 's1',
  },
  {
    id: 't3',
    project_id: 'p1',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment.',
    status: 'todo',
    priority: 'high',
    assignee_ids: ['3', '6'],
    assignees: [MOCK_USERS[2], MOCK_USERS[5]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-06',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-24T10:00:00Z',
    comment_count: 1,
    order_index: 2,
    labels: ['feature', 'enhancement'],
    story_points: 8,
    sprint_id: 's1',
  },
  {
    id: 't4',
    project_id: 'p1',
    title: 'Write API documentation',
    description: 'Document all REST endpoints using OpenAPI/Swagger.',
    status: 'code_review',
    priority: 'medium',
    assignee_ids: ['6'],
    assignees: [MOCK_USERS[5]],
    reporter_id: '2',
    reporter: MOCK_USERS[1],
    due_date: '2026-04-04',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-31T10:00:00Z',
    comment_count: 2,
    order_index: 3,
    labels: ['documentation'],
    story_points: 3,
    sprint_id: 's1',
  },
  {
    id: 't5',
    project_id: 'p1',
    title: 'Performance optimization',
    description: 'Profile and optimize slow queries and frontend bundle size.',
    status: 'testing',
    priority: 'low',
    assignee_ids: ['3', '5'],
    assignees: [MOCK_USERS[2], MOCK_USERS[4]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-07',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-04-01T10:00:00Z',
    comment_count: 4,
    order_index: 4,
    labels: ['enhancement'],
    story_points: 5,
    sprint_id: 's1',
  },
  {
    id: 't6',
    project_id: 'p2',
    title: 'Create design system components',
    description: 'Build a reusable component library for the mobile app.',
    status: 'in_progress',
    priority: 'critical',
    assignee_ids: ['4'],
    assignees: [MOCK_USERS[3]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-06',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-31T10:00:00Z',
    comment_count: 8,
    order_index: 0,
    labels: ['design', 'feature'],
    story_points: 13,
    sprint_id: 's1',
  },
  {
    id: 't7',
    project_id: 'p1',
    title: 'User role permission matrix',
    description: 'Define and implement role-based access control for admin, lead, developer, QA, and designer roles.',
    status: 'backlog',
    priority: 'high',
    assignee_ids: ['2'],
    assignees: [MOCK_USERS[1]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-18',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    comment_count: 1,
    order_index: 0,
    labels: ['feature', 'enhancement'],
    story_points: 8,
  },
  {
    id: 't8',
    project_id: 'p1',
    title: 'Fix login page crash on Safari',
    description: 'The login page throws a JavaScript error on Safari 16+ browsers. Root cause traced to Promise.allSettled polyfill.',
    status: 'backlog',
    priority: 'critical',
    assignee_ids: ['3'],
    assignees: [MOCK_USERS[2]],
    reporter_id: '5',
    reporter: MOCK_USERS[4],
    due_date: '2026-04-10',
    created_at: '2026-03-28T10:00:00Z',
    updated_at: '2026-03-28T10:00:00Z',
    comment_count: 3,
    order_index: 1,
    labels: ['bug', 'hotfix'],
    story_points: 3,
  },
  {
    id: 't9',
    project_id: 'p2',
    title: 'Mobile navigation bottom bar',
    description: 'Design and implement the bottom navigation bar for the mobile app redesign.',
    status: 'todo',
    priority: 'high',
    assignee_ids: ['4', '6'],
    assignees: [MOCK_USERS[3], MOCK_USERS[5]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-05',
    created_at: '2026-03-24T10:00:00Z',
    updated_at: '2026-03-24T10:00:00Z',
    comment_count: 2,
    order_index: 1,
    labels: ['design', 'feature'],
    story_points: 5,
    sprint_id: 's1',
  },
  {
    id: 't10',
    project_id: 'p1',
    title: 'Integrate Sentry error monitoring',
    description: 'Add Sentry SDK for real-time error tracking and performance monitoring.',
    status: 'code_review',
    priority: 'medium',
    assignee_ids: ['3'],
    assignees: [MOCK_USERS[2]],
    reporter_id: '2',
    reporter: MOCK_USERS[1],
    due_date: '2026-04-03',
    created_at: '2026-03-25T10:00:00Z',
    updated_at: '2026-04-01T10:00:00Z',
    comment_count: 3,
    order_index: 0,
    labels: ['enhancement'],
    story_points: 5,
    sprint_id: 's1',
  },
  {
    id: 't11',
    project_id: 'p1',
    title: 'Write E2E tests for auth flow',
    description: 'Use Playwright to write end-to-end tests covering login, signup, and password reset flows.',
    status: 'testing',
    priority: 'high',
    assignee_ids: ['5'],
    assignees: [MOCK_USERS[4]],
    reporter_id: '2',
    reporter: MOCK_USERS[1],
    due_date: '2026-04-07',
    created_at: '2026-03-26T10:00:00Z',
    updated_at: '2026-04-01T10:00:00Z',
    comment_count: 1,
    order_index: 1,
    labels: ['feature'],
    story_points: 8,
    sprint_id: 's1',
  },
  {
    id: 't12',
    project_id: 'p2',
    title: 'Responsive tablet layout',
    description: 'Optimize the dashboard and project list pages for tablet screen sizes.',
    status: 'backlog',
    priority: 'medium',
    assignee_ids: ['4'],
    assignees: [MOCK_USERS[3]],
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    due_date: '2026-04-21',
    created_at: '2026-03-22T10:00:00Z',
    updated_at: '2026-03-22T10:00:00Z',
    comment_count: 0,
    order_index: 2,
    labels: ['design', 'enhancement'],
    story_points: 5,
  },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: 'i1',
    project_id: 'p1',
    title: 'Login page crashes on Safari',
    description: 'The login page throws a JavaScript error on Safari 16+ browsers.',
    type: 'bug',
    severity: 'major',
    status: 'open',
    reporter_id: '4',
    reporter: MOCK_USERS[3],
    assignee_id: '3',
    assignee: MOCK_USERS[2],
    steps_to_reproduce: '1. Open Safari 16+\n2. Navigate to /login\n3. Enter credentials\n4. Click Sign in',
    created_at: '2024-03-20T10:00:00Z',
    updated_at: '2024-03-20T10:00:00Z',
    comment_count: 2,
  },
  {
    id: 'i2',
    project_id: 'p1',
    title: 'Add dark mode support',
    description: 'Users have requested dark mode as a feature.',
    type: 'feature_request',
    severity: 'minor',
    status: 'in_progress',
    reporter_id: '1',
    reporter: MOCK_USERS[0],
    assignee_id: '4',
    assignee: MOCK_USERS[3],
    created_at: '2024-03-15T10:00:00Z',
    updated_at: '2024-03-22T10:00:00Z',
    comment_count: 5,
  },
  {
    id: 'i3',
    project_id: 'p2',
    title: 'Slow image loading on mobile',
    description: 'Images take too long to load on 3G connections.',
    type: 'improvement',
    severity: 'major',
    status: 'open',
    reporter_id: '5',
    reporter: MOCK_USERS[4],
    created_at: '2024-03-18T10:00:00Z',
    updated_at: '2024-03-18T10:00:00Z',
    comment_count: 1,
  },
  {
    id: 'i4',
    project_id: 'p1',
    title: 'API rate limiter not resetting',
    description: 'The rate limiter counter is not being reset after the window period.',
    type: 'bug',
    severity: 'critical',
    status: 'open',
    reporter_id: '2',
    reporter: MOCK_USERS[1],
    assignee_id: '3',
    assignee: MOCK_USERS[2],
    steps_to_reproduce: '1. Make 100 API calls within 1 minute\n2. Wait 60 seconds\n3. Try to make another call',
    created_at: '2024-03-21T10:00:00Z',
    updated_at: '2024-03-21T10:00:00Z',
    comment_count: 4,
  },
];

export const MOCK_INVITATIONS: Invitation[] = [
  {
    id: 'inv1',
    email: 'alice.brown@company.com',
    role: 'developer',
    status: 'pending',
    invited_by: '1',
    token: 'tok1',
    sent_at: '2024-03-24T10:00:00Z',
    expires_at: '2024-03-31T10:00:00Z',
  },
  {
    id: 'inv2',
    email: 'bob.smith@company.com',
    role: 'designer',
    status: 'accepted',
    invited_by: '1',
    token: 'tok2',
    sent_at: '2024-03-20T10:00:00Z',
    expires_at: '2024-03-27T10:00:00Z',
    accepted_at: '2024-03-21T10:00:00Z',
  },
  {
    id: 'inv3',
    email: 'carol.white@company.com',
    role: 'qa',
    status: 'pending',
    invited_by: '1',
    token: 'tok3',
    sent_at: '2024-03-23T10:00:00Z',
    expires_at: '2024-03-30T10:00:00Z',
  },
  {
    id: 'inv4',
    email: 'david.jones@company.com',
    role: 'project_lead',
    status: 'expired',
    invited_by: '1',
    token: 'tok4',
    sent_at: '2024-03-10T10:00:00Z',
    expires_at: '2024-03-17T10:00:00Z',
  },
  {
    id: 'inv5',
    email: 'emma.wilson@company.com',
    role: 'designer',
    status: 'pending',
    invited_by: '1',
    token: 'tok5',
    sent_at: '2024-03-25T10:00:00Z',
    expires_at: '2024-04-01T10:00:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    user_id: '1',
    type: 'task_assigned',
    title: 'Task Assigned',
    message: 'Sarah Johnson assigned you to "Implement OAuth 2.0"',
    read: false,
    entity_type: 'task',
    entity_id: 't1',
    actor: MOCK_USERS[1],
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'n2',
    user_id: '1',
    type: 'comment_added',
    title: 'New Comment',
    message: 'Michael Chen commented on "Design user onboarding flow"',
    read: false,
    entity_type: 'task',
    entity_id: 't2',
    actor: MOCK_USERS[2],
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'n3',
    user_id: '1',
    type: 'status_changed',
    title: 'Status Updated',
    message: 'Task "Write API documentation" moved to Review',
    read: true,
    entity_type: 'task',
    entity_id: 't4',
    actor: MOCK_USERS[5],
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'n4',
    user_id: '1',
    type: 'deadline_approaching',
    title: 'Deadline Approaching',
    message: 'Task "Write API documentation" is due in 2 days',
    read: true,
    entity_type: 'task',
    entity_id: 't4',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'al1',
    user_id: '2',
    user: MOCK_USERS[1],
    action: 'Created account',
    entity_type: 'user',
    entity_id: '2',
    entity_name: 'Sarah Johnson',
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'al2',
    user_id: '3',
    user: MOCK_USERS[2],
    action: 'Updated profile',
    entity_type: 'user',
    entity_id: '3',
    entity_name: 'Michael Chen',
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'al3',
    user_id: '4',
    user: MOCK_USERS[3],
    action: 'Accepted invitation',
    entity_type: 'invitation',
    entity_id: 'inv2',
    entity_name: 'Emily Davis',
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'al4',
    user_id: '5',
    user: MOCK_USERS[4],
    action: 'Password reset',
    entity_type: 'user',
    entity_id: '5',
    entity_name: 'James Wilson',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'al5',
    user_id: '1',
    user: MOCK_USERS[0],
    action: 'Role changed to Admin',
    entity_type: 'user',
    entity_id: '6',
    entity_name: 'Lisa Anderson',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    entity_type: 'task',
    entity_id: 't1',
    author_id: '2',
    author: MOCK_USERS[1],
    content: 'Great progress on the OAuth implementation! The Google provider is working well. Can we also add GitHub OAuth in the same PR?',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    entity_type: 'task',
    entity_id: 't1',
    author_id: '3',
    author: MOCK_USERS[2],
    content: 'Sure! I\'ll add GitHub OAuth in the same PR. It should be straightforward with Supabase.',
    parent_id: 'c1',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    entity_type: 'task',
    entity_id: 't2',
    author_id: '1',
    author: MOCK_USERS[0],
    content: 'Emily, please make sure the Figma designs include mobile breakpoints. We need at least 375px, 768px, and 1440px variants.',
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c4',
    entity_type: 'task',
    entity_id: 't2',
    author_id: '4',
    author: MOCK_USERS[3],
    content: 'On it! I\'ll share the Figma link once the mobile frames are ready. Should have them by EOD tomorrow.',
    parent_id: 'c3',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c5',
    entity_type: 'task',
    entity_id: 't4',
    author_id: '2',
    author: MOCK_USERS[1],
    content: 'Please use OpenAPI 3.1 format and include example request/response bodies for each endpoint.',
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c6',
    entity_type: 'task',
    entity_id: 't10',
    author_id: '2',
    author: MOCK_USERS[1],
    content: 'PR looks good overall. One minor concern: the Sentry DSN is hardcoded. Please move it to env variables before merging.',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c7',
    entity_type: 'task',
    entity_id: 't10',
    author_id: '3',
    author: MOCK_USERS[2],
    content: 'Fixed! DSN is now loaded from VITE_SENTRY_DSN env variable. Ready for re-review.',
    parent_id: 'c6',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c8',
    entity_type: 'task',
    entity_id: 't11',
    author_id: '5',
    author: MOCK_USERS[4],
    content: 'All 24 E2E test cases passing in CI. Found one edge case with expired session handling — created a bug ticket for it.',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SPRINTS: Sprint[] = [
  {
    id: 's0',
    project_id: 'p1',
    name: 'Sprint 5 — Foundation',
    goal: 'Complete core authentication, CI/CD setup, and API documentation.',
    start_date: '2026-03-10',
    end_date: '2026-03-23',
    status: 'completed',
    created_at: '2026-03-09T10:00:00Z',
    total_story_points: 42,
    completed_story_points: 38,
    velocity: 38,
  },
  {
    id: 's1',
    project_id: 'p1',
    name: 'Sprint 6 — Integration',
    goal: 'Integrate Sentry monitoring, finalize CI/CD, complete E2E tests, and deliver QA-ready features.',
    start_date: '2026-03-24',
    end_date: '2026-04-07',
    status: 'active',
    created_at: '2026-03-23T10:00:00Z',
    total_story_points: 55,
    completed_story_points: 8,
    velocity: 0,
  },
  {
    id: 's2',
    project_id: 'p1',
    name: 'Sprint 7 — Polish & Launch',
    goal: 'Role-based permissions, mobile responsive layout, and bug fixes before v1.0 launch.',
    start_date: '2026-04-08',
    end_date: '2026-04-21',
    status: 'planning',
    created_at: '2026-04-01T10:00:00Z',
    total_story_points: 0,
    completed_story_points: 0,
  },
];

// Burndown data for the active sprint (s1): 15 days, total 55 SP
export const MOCK_BURNDOWN_DATA: BurndownPoint[] = [
  { day: 'Mar 24', ideal: 55, actual: 55 },
  { day: 'Mar 25', ideal: 51, actual: 52 },
  { day: 'Mar 26', ideal: 47, actual: 50 },
  { day: 'Mar 27', ideal: 43, actual: 47 },
  { day: 'Mar 28', ideal: 39, actual: 47 },
  { day: 'Mar 29', ideal: 35, actual: 47 },
  { day: 'Mar 30', ideal: 31, actual: 44 },
  { day: 'Mar 31', ideal: 27, actual: 47 },
  { day: 'Apr 1',  ideal: 23, actual: null },
  { day: 'Apr 2',  ideal: 19, actual: null },
  { day: 'Apr 3',  ideal: 15, actual: null },
  { day: 'Apr 4',  ideal: 11, actual: null },
  { day: 'Apr 5',  ideal: 7,  actual: null },
  { day: 'Apr 6',  ideal: 3,  actual: null },
  { day: 'Apr 7',  ideal: 0,  actual: null },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  total_users: 2847,
  active_users: 142,
  pending_invites: 23,
  admin_users: 8,
  total_projects: 4,
  active_projects: 2,
  total_tasks: 24,
  completed_tasks: 16,
  open_issues: 3,
  // Previous-month snapshots (used to compute MoM % change in stat cards)
  prev_total_users: 2531,
  prev_active_users: 136,
  prev_pending_invites: 29,
  prev_admin_users: 8,
};

export const MOCK_ROLE_DISTRIBUTION: RoleDistribution[] = [
  { role: 'admin', count: 8 },
  { role: 'project_lead', count: 12 },
  { role: 'designer', count: 45 },
  { role: 'developer', count: 124 },
  { role: 'qa', count: 32 },
];

export const MOCK_TASK_CHART_DATA = [
  { month: 'Oct', completed: 12, created: 18 },
  { month: 'Nov', completed: 19, created: 24 },
  { month: 'Dec', completed: 15, created: 20 },
  { month: 'Jan', completed: 22, created: 28 },
  { month: 'Feb', completed: 18, created: 22 },
  { month: 'Mar', completed: 25, created: 30 },
];

export const MOCK_BUG_TREND_DATA = [
  { week: 'W1', open: 8, closed: 5 },
  { week: 'W2', open: 12, closed: 8 },
  { week: 'W3', open: 7, closed: 11 },
  { week: 'W4', open: 9, closed: 7 },
  { week: 'W5', open: 4, closed: 9 },
  { week: 'W6', open: 6, closed: 4 },
];

// ─── Daily Scrum Mock Data ────────────────────────────────────────────────────

export const MOCK_STANDUP_SESSIONS: StandupSession[] = [
  {
    id: 'ss-1',
    project_id: '1',
    sprint_id: 'sprint-1',
    date: new Date().toISOString().split('T')[0],
    mode: 'async',
    status: 'in_progress',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    entries: [
      {
        id: 'se-1',
        session_id: 'ss-1',
        user_id: '1',
        user: undefined,
        yesterday: [
          { task_id: 'task-1', note: 'Completed the dashboard layout review' },
          { task_id: 'task-2', note: 'Merged PR for auth flow' },
        ],
        today: [
          { task_id: 'task-3', note: 'Starting API integration for reporting module' },
          { note: 'Team sync with design team at 3pm' },
        ],
        blockers: [],
        submitted_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
        attended: true,
        time_taken: 78,
      },
      {
        id: 'se-2',
        session_id: 'ss-1',
        user_id: '2',
        user: undefined,
        yesterday: [
          { task_id: 'task-4', note: 'Reviewed design tokens and Figma handoff' },
        ],
        today: [
          { task_id: 'task-5', note: 'Working on responsive layout for mobile' },
        ],
        blockers: [
          {
            id: 'sb-1',
            description: 'Waiting for API endpoint specs from backend team',
            task_id: 'task-5',
            severity: 'high',
            resolved: false,
            days_blocked: 2,
          },
        ],
        submitted_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
        attended: true,
        time_taken: 95,
      },
      {
        id: 'se-3',
        session_id: 'ss-1',
        user_id: '3',
        user: undefined,
        yesterday: [
          { note: 'Fixed critical bug in payment flow (#bug-291)' },
          { task_id: 'task-6', note: 'Unit tests for auth module' },
        ],
        today: [
          { task_id: 'task-7', note: 'Code review for PR #45' },
          { note: 'Update documentation for new API endpoints' },
        ],
        blockers: [
          {
            id: 'sb-2',
            description: 'CI pipeline failing intermittently — need DevOps access to check logs',
            severity: 'medium',
            resolved: false,
            days_blocked: 1,
          },
        ],
        submitted_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
        attended: true,
        time_taken: 112,
      },
      {
        id: 'se-4',
        session_id: 'ss-1',
        user_id: '4',
        user: undefined,
        yesterday: [],
        today: [],
        blockers: [],
        attended: false,
      },
      {
        id: 'se-5',
        session_id: 'ss-1',
        user_id: '5',
        user: undefined,
        yesterday: [],
        today: [],
        blockers: [],
        attended: false,
      },
    ],
    summary: {
      completed_tasks: 5,
      in_progress_tasks: 4,
      blockers_count: 2,
      attendees: 3,
      total_members: 5,
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ss-2',
    project_id: '1',
    sprint_id: 'sprint-1',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    mode: 'live',
    status: 'completed',
    meeting_link: 'https://zoom.us/j/123456789',
    started_at: new Date(Date.now() - 86400000 - 20 * 60 * 1000).toISOString(),
    ended_at: new Date(Date.now() - 86400000).toISOString(),
    entries: [
      {
        id: 'se-6',
        session_id: 'ss-2',
        user_id: '1',
        user: undefined,
        yesterday: [{ note: 'Reviewed sprint backlog and reprioritized items' }],
        today: [{ note: 'Sprint planning meeting and backlog grooming' }],
        blockers: [],
        submitted_at: new Date(Date.now() - 86400000).toISOString(),
        attended: true,
        time_taken: 65,
      },
      {
        id: 'se-7',
        session_id: 'ss-2',
        user_id: '2',
        user: undefined,
        yesterday: [{ task_id: 'task-1', note: 'Completed dashboard layout' }],
        today: [{ task_id: 'task-2', note: 'Auth flow implementation' }],
        blockers: [
          {
            id: 'sb-3',
            description: 'Need design approval for new color palette',
            severity: 'low',
            resolved: true,
            days_blocked: 0,
          },
        ],
        submitted_at: new Date(Date.now() - 86400000).toISOString(),
        attended: true,
        time_taken: 88,
      },
    ],
    summary: {
      completed_tasks: 8,
      in_progress_tasks: 6,
      blockers_count: 1,
      attendees: 5,
      total_members: 5,
      notes: 'Good velocity. Design blocker resolved during call. Team on track for sprint goal.',
    },
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ss-3',
    project_id: '1',
    sprint_id: 'sprint-1',
    date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    mode: 'async',
    status: 'completed',
    entries: [
      {
        id: 'se-8',
        session_id: 'ss-3',
        user_id: '1',
        yesterday: [{ note: 'Stakeholder presentation preparation' }],
        today: [{ note: 'Stakeholder demo and feedback collection' }],
        blockers: [],
        submitted_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        attended: true,
        time_taken: 55,
      },
    ],
    summary: {
      completed_tasks: 12,
      in_progress_tasks: 3,
      blockers_count: 0,
      attendees: 4,
      total_members: 5,
    },
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
